### PR TITLE
Fix unexpected packge creation error

### PR DESCRIPTION
**Pull request by ryo-yamaoka**
## WHAT

* Update `golang.org/x/tools` to latest

## WHY

The following error occurs when checking certain packages.

`paralleltest: Unexpected package creation during export data loading`

Maybe same as following issue.
I have updated that library and tested it in my local and it works correctly.

https://github.com/timonwong/loggercheck/pull/10

### CODE REVIEW

**Comment by ryo-yamaoka** [comment]
@kunwardeep Excuse me, would you review this PR and release it after the merge?

**Comment by ryo-yamaoka** [comment]
I started maintenance myself in forked repository.
If you restart maintenance please notice me

**Comment by kunwardeep** [comment]
Sorry mate.. just on my holidays. Will take care of this soon

**Comment by ryo-yamaoka** [comment]
oh, thanks for your response.
Okay, I'll recreate pull request!

**Comment by kunwardeep** [comment]
Hey, @ryo-yamaoka Did you want to reopen the PR? Your original branch seems deleted

**Pull request closed without merging**
